### ISSUE TITLE
Não consigo exportar produtos e clientes

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/app-mailchimp#20]
empresa com ID 1284 fiz todas as configurações em uma nova compra do MailChimp.
Quando vou exportar a lista de produto, ele retorna exportado com sucesso, mas não gera nada lá no MailChimp.
Aqui eu fui registrando o passo a passo que eu Fiz ate chegar no momento da exportação: 
https://community.e-com.plus/t/mailchimp-como-configurar/1829/3
Se precisar de usuário e senha para acesso na plataforma ou MailChimp me procure ou o Matheus

**Comment by leomp12** [comment]
Quando foi isso? Vocês testaram? Tá muito vago esse issue 😐
