### ISSUE TITLE
App: Mailchimp

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-mailchimp#4]
- [x] Setup do repo (falta o token de parceiro);
- [x] Configuração do app seguindo instruções em next steps;
- [x] Integração com o Mailchimp via [API 3.0 seção E-commerce Stores](https://mailchimp.com/developer/reference/ecommerce-stores/): sincronizar carrinhos, produtos e clientes (a sugestão é usar Procedures da Store API);
- [ ] Descrição e um ícone legal (@vitorrgg ) pro Market;

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-mailchimp/commit/123206544c9c189bb980c052a9bc1cdd4b248000

**Comment by leomp12** [comment]
Não rolou @talissonf , parece que tem algum problema na function:
https://github.com/ecomplus/app-mailchimp/runs/686399091

**Comment by talissonf** [comment]
É eu vi isso mas se rodar um re-run ele faz deploy :thinking: 
https://github.com/ecomplus/app-mailchimp/actions/runs/108467131

**Comment by talissonf** [comment]
Fiz uma view para o aplicativo no admin 
https://github.com/ecomplus/admin-marketplace/pull/99

**Comment by leomp12** [comment]
@vitorrgg desembola o ícone aí pra nós por favor

**Comment by vitorrgg** [comment]
![mailchimp](https://user-images.githubusercontent.com/35348281/82359313-1efe6780-99de-11ea-9751-d6c9629be9ee.png)

**Comment by leomp12** [comment]
@talissonf você pode criar a descrição e publicar o app pra nós por favor?
No https://app-dev.e-com.plus já deve aparecer a view do Mailchimp no marketplace, daqui a pouco jogamos pra produção também.

**Comment by talissonf** [comment]
@leomp12 posso sim!

**Comment by talissonf** [comment]
publiquei

**Comment by leomp12** [comment]
@talissonf valeu!
